version: '2'
services:
  cwn-basic-zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: cwn-basic-zookeeper
    ports: 
      - "2181:2181"
    volumes: 
      - /home/codewithneeraj/container-data/zookeeper:/bitnami/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_ADMIN_SERVER_PORT_NUMBER=8887
    networks:
      - cwn-default-network
      
  cwn-basic-kafka:
    image: 'bitnami/kafka:latest'
    container_name: cwn-basic-kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=cwn-basic-zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
     
      # Part of custom settings
      - ALLOW_PLAINTEXT_LISTENER=yes
      # ssl
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093 #,SSL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://localhost:9093,CLIENT://localhost:9092 #SSL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:SSL,SSL:SSL,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.keystore.jks
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=kafka123
      - KAFKA_CFG_SSL_KEY_PASSWORD=kafka123
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.truststore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=kafka123
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
      - KAFKA_CFG_ZOOKEEPER_PROTOCOL=PLAINTEXT
      - KAFKA_SECURITY_PROTOCOL=SSL
      - KAFKA_SECURITY_INTER_BROKER_PROTOCOL=CLIENT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_TLS_CLIENT_AUTH=required
    volumes:
      - /home/codewithneeraj/certificate/kafka_cert/server.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro
      - /home/codewithneeraj/certificate/kafka_cert/server.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro
      - /home/codewithneeraj/container-data/kafka:/bitnami/kafka/data

    depends_on:
      - cwn-basic-zookeeper
    networks:
      - cwn-default-network

networks:
  cwn-default-network:
